### ISSUE TITLE
Хочу нажать на кнопочку и видеть список только моих задач

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/projectile#1]
Спасибо :)

**Comment by schaman** [comment]
Почему именно на кнопочку?

https://github.com/schaman/q/wiki#how-to-create-a-nice-issue

**Comment by kirilldudinsky** [comment]
Я делаю задачи и хочу, чтобы у меня было все в одном месте (а не на бумажках, как сейчас) и при этом чтобы Ты (и контролер) видел, чем я занимаюсь. 

Когда задачи написаны у меня на бумажке, мне видны только мои задачи. Зачем мне видеть чьи-то другие задачи в тот момент, когда я хочу сосредоточиться на своих и быстро их распланировать?

А кнопочка, потому что в бейскемпе и в старом теке было очень удобно посмотреть список моих задач.

**Comment by schaman** [comment]
готово
