### ISSUE TITLE
Хочу убрать человека из projectile'а

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/projectile#5]
Сейчас при выборе ответственного за задачу вылезает куча людей, с которыми мы давно не сотрудничаем.

![2015-07-18 18 20 01](https://cloud.githubusercontent.com/assets/9354450/8762467/d8fd3174-2d79-11e5-8555-dd74eecc611c.png)

Для того, чтобы "почистить" projectile, предлагаю реализовать механизм удаления человека, либо разово удалить следующих пользователей:
- Elena  
- Konstantin  
- Golubtsov  
- Averin  
- Kidpoker  
- Sacha22

**Comment by schaman** [comment]
Спрятал их
