### ISSUE TITLE
Удаляю задачу, а она снова отображается

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/projectile#6]
См. время на скриншотах

![2015-07-19 2 09 38](https://cloud.githubusercontent.com/assets/9354450/8764021/6f0ce100-2dbb-11e5-9682-e061cc19cd8d.png)
![2015-07-19 2 09 41](https://cloud.githubusercontent.com/assets/9354450/8764022/6f0fcb4a-2dbb-11e5-9eea-c9fdf6a61d49.png)

Нажал remove

![2015-07-19 2 09 58](https://cloud.githubusercontent.com/assets/9354450/8764023/6f13661a-2dbb-11e5-865f-a09d2d07e37a.png)
![2015-07-19 2 10 44](https://cloud.githubusercontent.com/assets/9354450/8764024/6f1570cc-2dbb-11e5-81fc-8c4ab0087f72.png)

**Comment by kirilldudinsky** [comment]
Почему-то [в этом проекте](http://projectile.icoach.io/#/project/1375620a-e1a6-4744-febc-fcc6072848bb) с несколькими задачами так

**Comment by kirilldudinsky** [comment]
[вот эта задача не хочет удаляться](http://projectile.icoach.io/#/project/102f0859-f0b2-41ac-2dba-894a4660a305/task/f3dd6b06-e3ab-4b2e-619c-ca41c8c82d94)

**Comment by schaman** [comment]
fixed. Удали, пожалуйста, те задачи, которые не удалялись.
